import { ACCENT, ACCENT_HEX, ACCENT_ON_DARK, FONT_MONO, FONT_UI } from '../constants.js';

export const LABEL_CSS = [

  // --- Icon mode: small dot, hover reveals tooltip ---
  '.stadiaref-ref-icon {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  position: absolute;',
  '  top: 2px;',
  '  left: 2px;',
  '  width: 16px;',
  '  height: 16px;',
  '  font-size: 12px;',
  '  line-height: 16px;',
  '  text-align: center;',
  '  background: rgba(' + ACCENT + ', 0.12);',
  '  color: rgba(' + ACCENT + ', 0.6);',
  '  border-radius: 50%;',
  '  z-index: 90;',
  '  cursor: pointer;',
  // pointer-events default is none; .stadiaref-visible-host opts in. See the
  // "Visible-host gate" rule near the bottom of this stylesheet — the
  // gate is added by applyLabelVisibilityState() only after a label has
  // been confirmed to sit inside an effectively-visible host. This
  // closes the click-intercept race documented in CHANGELOG v2.3.1.
  '  pointer-events: none;',
  '  transition: all 0.1s;',
  '  user-select: none;',
  '}',

  '.stadiaref-ref-icon:hover {',
  '  background: rgba(' + ACCENT + ', 0.25);',
  '  color: rgba(' + ACCENT + ', 0.9);',
  '}',

  // --- Tooltip (shown on icon hover only — not whole-element hover) ---
  '.stadiaref-ref-tooltip {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  position: absolute;',
  '  top: 2px;',
  '  left: 22px;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  line-height: 1;',
  '  padding: 3px 6px;',
  '  background: rgba(17, 24, 39, 0.85);',
  '  color: #FFF7ED;',
  '  border-radius: 3px;',
  '  z-index: 91;',
  '  white-space: nowrap;',
  '  opacity: 0;',
  '  transform: translateX(-4px);',
  '  transition: opacity 0.1s, transform 0.1s;',
  '  cursor: pointer;',
  '  pointer-events: none;',
  '  user-select: all;',
  '}',

  // Show tooltip when hovering the icon (not the whole element)
  '.stadiaref-ref-icon:hover + .stadiaref-ref-tooltip {',
  '  opacity: 1;',
  '  transform: translateX(0);',
  '  pointer-events: auto;',
  '}',

  // Keep tooltip visible when mouse moves onto it from the icon
  '.stadiaref-ref-tooltip:hover {',
  '  opacity: 1;',
  '  transform: translateX(0);',
  '  pointer-events: auto;',
  '}',

  // --- Full-label mode: high-contrast dark bg ---
  '.stadiaref-ref-full-label {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  position: absolute;',
  '  top: 2px;',
  '  left: 2px;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  line-height: 1;',
  '  padding: 2px 4px;',
  '  background: rgba(17, 24, 39, 0.82);',
  '  color: #FFF7ED;',
  '  border: 1px solid rgba(255, 255, 255, 0.1);',
  '  border-radius: 3px;',
  '  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);',
  '  z-index: 90;',
  '  cursor: pointer;',
  // pointer-events default is none; .stadiaref-visible-host opts in. See the
  // "Visible-host gate" rule near the bottom of this stylesheet.
  '  pointer-events: none;',
  '  user-select: all;',
  '  white-space: nowrap;',
  '  max-width: 220px;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '}',

  '.stadiaref-ref-full-label:hover {',
  '  background: rgba(234, 88, 12, 0.9);',
  '  color: #fff;',
  '  border-color: rgba(255, 255, 255, 0.2);',
  '}',

  // --- Element type tag prefix ---
  '.stadiaref-ref-tag {',
  '  all: initial;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: inherit;',
  '  font-weight: 600;',
  '  color: inherit;',
  '  opacity: 0.5;',
  '}',

  // --- Mode: hide-labels ---
  'body.stadiaref-hide .stadiaref-ref-icon,',
  'body.stadiaref-hide .stadiaref-ref-tooltip,',
  'body.stadiaref-hide .stadiaref-ref-full-label { display: none !important; }',

  // --- Mode: show-labels (full) — icon + tooltip hidden ---
  'body.stadiaref-full .stadiaref-ref-icon,',
  'body.stadiaref-full .stadiaref-ref-tooltip { display: none !important; }',

  // --- Default (icons): full label hidden ---
  'body:not(.stadiaref-full) .stadiaref-ref-full-label { display: none !important; }',

  // --- Presentation mode: hide everything ---
  'body.stadiaref-presentation .stadiaref-ref-icon,',
  'body.stadiaref-presentation .stadiaref-ref-tooltip,',
  'body.stadiaref-presentation .stadiaref-ref-full-label { display: none !important; }',

  // --- Adaptive: dark-background variant ---
  '.stadiaref-ref-icon.stadiaref-on-dark {',
  '  background: rgba(255, 255, 255, 0.18);',
  '  color: rgba(255, 255, 255, 0.85);',
  '}',
  '.stadiaref-ref-icon.stadiaref-on-dark:hover {',
  '  background: rgba(255, 255, 255, 0.32);',
  '  color: #fff;',
  '}',
  '.stadiaref-ref-full-label.stadiaref-on-dark {',
  '  background: rgba(255, 255, 255, 0.88);',
  '  color: #111827;',
  '  border-color: rgba(0, 0, 0, 0.08);',
  '}',
  '.stadiaref-ref-full-label.stadiaref-on-dark:hover {',
  '  background: #fff;',
  '  color: #EA580C;',
  '}',

  // Void-element host: <img>, <video>, <input> etc. cannot render children, so their
  // label nodes mount in a sibling span that mirrors the element's box (v2.5.0).
  '.stadiaref-ref-void-host {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  position: absolute;',
  '  pointer-events: none;',
  '  z-index: 95;',
  '}',
  'body.stadiaref-hide .stadiaref-ref-void-host,',
  'body.stadiaref-presentation .stadiaref-ref-void-host {',
  '  display: none !important;',
  '}',

  '.stadiaref-ref-link {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  position: absolute;',
  '  top: 2px;',
  '  left: 9px;',
  '  width: 1px;',
  '  height: 0;',
  '  background: rgba(' + ACCENT + ', 0.55);',
  '  z-index: 89;',
  '  pointer-events: none;',
  '  opacity: 0;',
  '}',
  '.stadiaref-ref-link.stadiaref-on-dark {',
  '  background: rgba(255, 255, 255, 0.62);',
  '}',

  // --- Tree panel: element highlight on row hover ---
  '.stadiaref-tree-highlight {',
  '  outline: 2px solid #EA580C !important;',
  '  outline-offset: 3px !important;',
  '}',
  '.stadiaref-tree-jump-highlight {',
  '  outline: 3px solid rgba(' + ACCENT + ', 0.92) !important;',
  '  outline-offset: 4px !important;',
  '  box-shadow: 0 0 0 6px rgba(' + ACCENT + ', 0.16) !important;',
  '}',

  // --- Outline guides ---
  '.stadiaref-outline-section {',
  '  outline: 2px solid rgba(' + ACCENT + ', 0.90) !important;',
  '  outline-offset: -2px !important;',
  '  box-shadow: inset 0 0 0 1px rgba(' + ACCENT + ', 0.20), inset 0 18px 0 0 rgba(' + ACCENT + ', 0.08) !important;',
  '}',
  '.stadiaref-outline-block {',
  '  outline: 1px dashed rgba(' + ACCENT + ', 0.46) !important;',
  '  outline-offset: -1px !important;',
  '  box-shadow: inset 0 0 0 1px rgba(' + ACCENT + ', 0.08) !important;',
  '}',
  '.stadiaref-outline-section.stadiaref-outline-on-dark {',
  '  outline-color: rgba(' + ACCENT_ON_DARK + ', 0.98) !important;',
  '  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.14), inset 0 18px 0 0 rgba(' + ACCENT_ON_DARK + ', 0.12) !important;',
  '}',
  '.stadiaref-outline-block.stadiaref-outline-on-dark {',
  '  outline-color: rgba(255, 255, 255, 0.36) !important;',
  '  box-shadow: inset 0 0 0 1px rgba(' + ACCENT_ON_DARK + ', 0.14) !important;',
  '}',
  'body.stadiaref-presentation .stadiaref-outline-section,',
  'body.stadiaref-presentation .stadiaref-outline-block {',
  '  outline: none !important;',
  '  box-shadow: none !important;',
  '}',
  'body.stadiaref-hide .stadiaref-ref-link,',
  'body.stadiaref-presentation .stadiaref-ref-link {',
  '  display: none !important;',
  '}',

  // --- Hidden-ancestor suppression ---
  // Labels for [data-ref] elements whose ancestors are display:none,
  // visibility:hidden, or opacity:0 are hidden so invisible icons don't
  // intercept clicks on visible page content beneath them. Toggled by
  // applyLabelVisibilityState() and re-evaluated via MutationObserver.
  '.stadiaref-ref-icon.stadiaref-ref-hidden,',
  '.stadiaref-ref-tooltip.stadiaref-ref-hidden,',
  '.stadiaref-ref-full-label.stadiaref-ref-hidden,',
  '.stadiaref-ref-link.stadiaref-ref-hidden {',
  '  display: none !important;',
  '}',

  // --- Visible-host gate (the structural belt) ---
  // Icon / full-label / link labels default to pointer-events: none
  // (see their base rules above). They opt back in to pointer-events:
  // auto only when applyLabelVisibilityState() has confirmed their
  // host is effectively visible and adds this class. The reactive
  // .stadiaref-ref-hidden toggle (display:none) is the timing brace; this
  // class is the structural belt — even if the reactive layer races
  // (e.g. during a mid-transition rAF tick reading an animated opacity
  // value), labels can never intercept clicks unless explicitly
  // marked safe.
  '.stadiaref-ref-icon.stadiaref-visible-host,',
  '.stadiaref-ref-full-label.stadiaref-visible-host {',
  '  pointer-events: auto;',
  '}',

  // --- Cluster collapse ("+N" badge) ---
  // When the overlap solver can't find a non-colliding slot for a
  // label after LABEL_OFFSET_LIMIT attempts, it stashes the label on
  // the colliding owner's cluster list and renders a single "+N"
  // badge next to the owner's active label. Hovering the badge
  // expands a popover listing the clustered refs. Each row is
  // click-to-copy with the same semantics as a normal label. Solves
  // the "wall of stacked labels" on dense pages where nested refs
  // share the same anchor position (e.g. an `<article>` containing
  // an `<h3>` and `<p>`, all with data-ref).
  '.stadiaref-ref-clustered {',
  '  display: none !important;',
  '}',
  '.stadiaref-cluster-badge {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  position: absolute;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  font-weight: 600;',
  '  line-height: 1;',
  '  padding: 2px 5px;',
  '  background: rgba(' + ACCENT + ', 0.18);',
  '  color: ' + ACCENT_HEX + ';',
  '  border: 1px solid rgba(' + ACCENT + ', 0.32);',
  '  border-radius: 10px;',
  '  cursor: pointer;',
  '  z-index: 92;',
  '  pointer-events: auto;',
  '  user-select: none;',
  '  white-space: nowrap;',
  '}',
  '.stadiaref-cluster-badge:hover {',
  '  background: rgba(' + ACCENT + ', 0.92);',
  '  color: #fff;',
  '  border-color: rgba(' + ACCENT + ', 0.92);',
  '}',
  '.stadiaref-cluster-badge.stadiaref-on-dark {',
  '  background: rgba(255, 255, 255, 0.18);',
  '  color: rgba(255, 255, 255, 0.92);',
  '  border-color: rgba(255, 255, 255, 0.32);',
  '}',
  '.stadiaref-cluster-badge.stadiaref-on-dark:hover {',
  '  background: #fff;',
  '  color: ' + ACCENT_HEX + ';',
  '  border-color: #fff;',
  '}',
  '.stadiaref-cluster-popover {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  display: none;',
  '  flex-direction: column;',
  '  position: absolute;',
  '  top: 100%;',
  '  left: 0;',
  '  margin-top: 4px;',
  '  min-width: 180px;',
  '  max-width: 320px;',
  '  background: rgba(17, 24, 39, 0.96);',
  '  border: 1px solid rgba(255, 255, 255, 0.1);',
  '  border-radius: 4px;',
  '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.24);',
  '  padding: 4px;',
  '  z-index: 93;',
  '  pointer-events: auto;',
  '}',
  '.stadiaref-cluster-badge:hover > .stadiaref-cluster-popover,',
  '.stadiaref-cluster-popover:hover {',
  '  display: flex;',
  '}',
  '.stadiaref-cluster-item {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  display: flex;',
  '  align-items: baseline;',
  '  gap: 6px;',
  '  padding: 4px 6px;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  line-height: 1.3;',
  '  color: #FFF7ED;',
  '  cursor: pointer;',
  '  border-radius: 3px;',
  '  white-space: nowrap;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '}',
  '.stadiaref-cluster-item:hover {',
  '  background: rgba(' + ACCENT + ', 0.92);',
  '  color: #fff;',
  '}',
  '.stadiaref-cluster-item-tag {',
  '  all: initial;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  font-weight: 600;',
  '  color: inherit;',
  '  opacity: 0.55;',
  '  flex-shrink: 0;',
  '}',
  '.stadiaref-cluster-item-ref {',
  '  all: initial;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  color: inherit;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '  white-space: nowrap;',
  '}',
  'body.stadiaref-hide .stadiaref-cluster-badge,',
  'body.stadiaref-presentation .stadiaref-cluster-badge {',
  '  display: none !important;',
  '}',

  // --- Level filter: Sections only ---
  // body.stadiaref-filter-section hides icons/labels/badges on non-section refs.
  // The class is set on body by applyLevelFilter(); the stadiaref-ref-class-*
  // classes are added to [data-ref] elements by injectLabels().
  'body.stadiaref-filter-section [data-ref]:not(.stadiaref-ref-class-section) .stadiaref-ref-icon,',
  'body.stadiaref-filter-section [data-ref]:not(.stadiaref-ref-class-section) .stadiaref-ref-full-label,',
  'body.stadiaref-filter-section [data-ref]:not(.stadiaref-ref-class-section) .stadiaref-ref-tooltip,',
  'body.stadiaref-filter-section [data-ref]:not(.stadiaref-ref-class-section) .stadiaref-cluster-badge {',
  '  display: none !important;',
  '}',

  // --- Level filter: Sections + Blocks ---
  'body.stadiaref-filter-section-block [data-ref]:not(.stadiaref-ref-class-section):not(.stadiaref-ref-class-block) .stadiaref-ref-icon,',
  'body.stadiaref-filter-section-block [data-ref]:not(.stadiaref-ref-class-section):not(.stadiaref-ref-class-block) .stadiaref-ref-full-label,',
  'body.stadiaref-filter-section-block [data-ref]:not(.stadiaref-ref-class-section):not(.stadiaref-ref-class-block) .stadiaref-ref-tooltip,',
  'body.stadiaref-filter-section-block [data-ref]:not(.stadiaref-ref-class-section):not(.stadiaref-ref-class-block) .stadiaref-cluster-badge {',
  '  display: none !important;',
  '}',

  // --- Block group collapse badge ---
  // When a section has >6 block-class refs and level filter is "All",
  // those blocks are collapsed. Their individual labels are hidden;
  // a "+N blocks" badge is placed on the section instead.
  '.stadiaref-ref-block-group-member .stadiaref-ref-icon,',
  '.stadiaref-ref-block-group-member .stadiaref-ref-full-label,',
  '.stadiaref-ref-block-group-member .stadiaref-ref-tooltip {',
  '  display: none !important;',
  '}',

  '.stadiaref-block-group-badge {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  position: absolute;',
  '  z-index: 92;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  font-weight: 600;',
  '  line-height: 1;',
  '  padding: 3px 7px;',
  '  border-radius: 999px;',
  '  cursor: pointer;',
  '  white-space: nowrap;',
  '  user-select: none;',
  '}',

  '.stadiaref-block-group-badge.stadiaref-on-light {',
  '  background: rgba(' + ACCENT + ', 0.12);',
  '  color: ' + ACCENT_HEX + ';',
  '}',

  '.stadiaref-block-group-badge.stadiaref-on-dark {',
  '  background: rgba(' + ACCENT_ON_DARK + ', 0.20);',
  '  color: #FDBA74;',
  '}',

  '.stadiaref-block-group-popover {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  display: none;',
  '  position: absolute;',
  '  top: calc(100% + 4px);',
  '  left: 0;',
  '  background: #111827;',
  '  border: 1px solid rgba(255,255,255,0.1);',
  '  border-radius: 5px;',
  '  padding: 4px 0;',
  '  min-width: 180px;',
  '  max-width: 280px;',
  '  z-index: 93;',
  '}',

  '.stadiaref-block-group-badge:hover .stadiaref-block-group-popover { display: block; }',

  '.stadiaref-block-group-item {',
  '  all: initial;',
  '  box-sizing: border-box;',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 8px;',
  '  padding: 4px 10px;',
  '  cursor: pointer;',
  '}',

  '.stadiaref-block-group-item:hover { background: rgba(255,255,255,0.06); }',

  '.stadiaref-block-group-item-type {',
  '  all: initial;',
  '  font-family: ' + FONT_UI + ';',
  '  font-size: 9px;',
  '  font-weight: 600;',
  '  text-transform: uppercase;',
  '  letter-spacing: 0.4px;',
  '  color: rgba(' + ACCENT_ON_DARK + ', 0.75);',
  '  white-space: nowrap;',
  '}',

  '.stadiaref-block-group-item-ref {',
  '  all: initial;',
  '  font-family: ' + FONT_MONO + ';',
  '  font-size: 10px;',
  '  color: #D1D5DB;',
  '  white-space: nowrap;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '  max-width: 200px;',
  '}',

  'body.stadiaref-hide .stadiaref-block-group-badge,',
  'body.stadiaref-presentation .stadiaref-block-group-badge {',
  '  display: none !important;',
  '}',

].join('\n');
